import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useForm } from "react-hook-form";
import Favicon from "../public/images/favIcon.png"
//components
import NavbarMenu from '../components/navbar'
import LandingPage from '../components/LandingPage'
import CountUpp from '../components/countUp'
import Earn from '../components/Earn'
import Footer from '../components/Footer'
import Sentiments from '../components/sentiments/Sentiments'
import Subscribe from '../components/Subscribe'
import WhyChoose from '../components/WhyChoose'


export default function Home() {

  
  return (
    <div className={styles.container}>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={Favicon.src} />
      </Head>
      <NavbarMenu/>

    <main>
      <div>
        <LandingPage/>

        <CountUpp/>
        <WhyChoose/>
        <Earn/>
        <Sentiments/>
      </div>
    </main>

     <Footer/>
    </div>
  )
}
